version: '3.7'
services:
  fluxday-db:
    #container_name: fluxday-db
    image: mysql:5.6
    env_file:
      - db.env

  fluxday-app:
    #container_name: fluxday-app
    image: trinhpham/fluxday
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes: #Use this option is for dev only
      - .:/share
    env_file:
      - app.env
    depends_on:
      - fluxday-db
    ports:
      - 3000:3000
